"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { useState } from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Longs Parfa Nansok",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [toggle, setToggle] = useState(false);

  function hideMenu() {
    setToggle(false);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header toggle={toggle} setToggle={setToggle} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
